CREATE ROLE web_anon NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOLOGIN;

GRANT USAGE ON SCHEMA acl TO web_anon;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA acl TO web_anon;

GRANT EXECUTE
ON ALL ROUTINES IN SCHEMA acl TO web_anon;

REVOKE INSERT, UPDATE, DELETE ON TABLE permission_cache FROM web_anon;
REVOKE INSERT, UPDATE, DELETE ON TABLE perm_tree FROM web_anon;